name: Deploy via FTP
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist
        server-dir: /